grep -c GG.TTNGATACCC..GTA RRNA_Bact_Archaea.fasta
grep -c TTNGATACCC..GTA.TC RRNA_Bact_Archaea.fasta
grep -c TG.CAGC.GCCGCGGT.A RRNA_Bact_Archaea.fasta
grep -c G.TTNGATACCC..GTAG RRNA_Bact_Archaea.fasta
grep -c CAGC.GCCGCGGT.A.AC RRNA_Bact_Archaea.fasta
grep -c TNGATACCC..GTA.TCC RRNA_Bact_Archaea.fasta
grep -c GTG.CAGC.GC.GCGGTA RRNA_Bact_Archaea.fasta
grep -c CCAGC.GCCGCGGT.A.A RRNA_Bact_Archaea.fasta
grep -c CT.AAA.NAATTG.CGGG RRNA_Bact_Archaea.fasta
grep -c ACT.AAA.NAATTG.CGG RRNA_Bact_Archaea.fasta
grep -c GGATTNGA.ACCC..GTA RRNA_Bact_Archaea.fasta
grep -c AACT.AAA.NAATTG.CG RRNA_Bact_Archaea.fasta
grep -c ATTNGATACCC..GTA.T RRNA_Bact_Archaea.fasta
grep -c AAACT.AAA.NAATTG.C RRNA_Bact_Archaea.fasta
grep -c T.AAACT.AAA.NAATTG RRNA_Bact_Archaea.fasta
grep -c C.AA..GGATTNGATACC RRNA_Bact_Archaea.fasta
grep -c T.AAA.NAATTG.CGGGG RRNA_Bact_Archaea.fasta
grep -c CGTCAGCTCGT...GTGA RRNA_Bact_Archaea.fasta
grep -c CATGG..G.CGTCAGCTC RRNA_Bact_Archaea.fasta
grep -c GCATGG..G.CGTCAGCT RRNA_Bact_Archaea.fasta
grep -c TGG..G.CGTCAGCTCGT RRNA_Bact_Archaea.fasta
grep -c ATGG..G.CGTCAGCTCG RRNA_Bact_Archaea.fasta
grep -c TGCATGG..G.CGTCAGC RRNA_Bact_Archaea.fasta
grep -c GTCG.CAGCTCGTG..GT RRNA_Bact_Archaea.fasta
grep -c TCG.CAGCTCGTG..GTG RRNA_Bact_Archaea.fasta
grep -c GG..GTCG.CAGCTCGTG RRNA_Bact_Archaea.fasta
grep -c TTG.AC.CAC.GCCCGTC RRNA_Bact_Archaea.fasta
grep -c T..GTGCCAGCAGC.GCG RRNA_Bact_Archaea.fasta
grep -c CTTG.AC.CAC.GCCCGT RRNA_Bact_Archaea.fasta
grep -c A.T..GTGCCAGCAGCCG RRNA_Bact_Archaea.fasta
grep -c AC.GG.TTNGATACCC.G RRNA_Bact_Archaea.fasta
grep -c C.GG.TTNGATACCC.GG RRNA_Bact_Archaea.fasta
grep -c AA.T..GTGCCAGCAGCC RRNA_Bact_Archaea.fasta
grep -c TG.AC.CAC.GCCCGTCA RRNA_Bact_Archaea.fasta
grep -c G.CAGC.GCCGCGGT.AT RRNA_Bact_Archaea.fasta
grep -c C...AACGAGCGCAACCC RRNA_Bact_Archaea.fasta
grep -c G.TGCATGG..GTCGTCA RRNA_Bact_Archaea.fasta
grep -c TCCT.CGGGAG..AGCAG RRNA_Bact_Archaea.fasta
grep -c GGTTNAGTCC...AACGA RRNA_Bact_Archaea.fasta
grep -c TNAGTCC...AACGAGCG RRNA_Bact_Archaea.fasta
grep -c GTTNAGTCC...AACGAG RRNA_Bact_Archaea.fasta
grep -c TTNAGTCC...AACGAGC RRNA_Bact_Archaea.fasta
grep -c TG.TGCATGG..GTCGTC RRNA_Bact_Archaea.fasta
grep -c CACACCGCCCGTCA...C RRNA_Bact_Archaea.fasta
grep -c TTAATTCGA.GN.AC.CG RRNA_Bact_Archaea.fasta
grep -c AGGAAGG.G.GGA.GACG RRNA_Bact_Archaea.fasta
grep -c CAGCCGCGGTAA.AC..A RRNA_Bact_Archaea.fasta
grep -c GAGGAAGG.G.GGA.GAC RRNA_Bact_Archaea.fasta
grep -c NAGTCC...AACGAGCGC RRNA_Bact_Archaea.fasta
grep -c ACACCGCCCGTCA...CA RRNA_Bact_Archaea.fasta
grep -c GGAAGG.G.GGA.GACGT RRNA_Bact_Archaea.fasta
grep -c AGTCC...AACGAGCGCA RRNA_Bact_Archaea.fasta
grep -c CC...AACGAGCGCAACC RRNA_Bact_Archaea.fasta
grep -c GGTG.TGCATGG..GTCG RRNA_Bact_Archaea.fasta
grep -c AGGTG.TGCATGG..GTC RRNA_Bact_Archaea.fasta
grep -c GTCC...AACGAGCGCAA RRNA_Bact_Archaea.fasta
grep -c GAAGG.G.GGA.GACGTC RRNA_Bact_Archaea.fasta
grep -c TCC...AACGAGCGCAAC RRNA_Bact_Archaea.fasta
grep -c GTG.TGCATGG..GTCGT RRNA_Bact_Archaea.fasta
grep -c C.CCTACGGG.GGC.GCA RRNA_Bact_Archaea.fasta
grep -c AA.NAATTGACGGGG..C RRNA_Bact_Archaea.fasta
grep -c GACGGGG..C.GCACAAG RRNA_Bact_Archaea.fasta
grep -c AC.CCTACGGG.GGC.GC RRNA_Bact_Archaea.fasta
grep -c CT..GTGCCAGCAGC.GC RRNA_Bact_Archaea.fasta
grep -c GGC.AACT..GTGCCAGC RRNA_Bact_Archaea.fasta
grep -c CCT.CGGG.GGC.GCAGT RRNA_Bact_Archaea.fasta
grep -c CN.AC.CCTACGGG.GGC RRNA_Bact_Archaea.fasta
grep -c G.TTAATTCGA.GN.ACG RRNA_Bact_Archaea.fasta
grep -c GC.AACT..GTGCCAGCA RRNA_Bact_Archaea.fasta
grep -c C.AACT..GTGCCAGCAG RRNA_Bact_Archaea.fasta
grep -c AAGG.G.GGA.GACGTCA RRNA_Bact_Archaea.fasta
grep -c TGTCGTCAG.TCGTG..G RRNA_Bact_Archaea.fasta
grep -c GGG.AGTACG..CGCAAG RRNA_Bact_Archaea.fasta
grep -c CCN.AC.CCTACGGG.GG RRNA_Bact_Archaea.fasta
grep -c N..CTCCT.CGGGAGGCA RRNA_Bact_Archaea.fasta
grep -c CGGC.AACT..GTGCCAG RRNA_Bact_Archaea.fasta
grep -c TGGG.AGTACG..CGCAA RRNA_Bact_Archaea.fasta
grep -c CTGGG.AGTACG..CGCA RRNA_Bact_Archaea.fasta
grep -c CGGGAGGC.GCAGT..GN RRNA_Bact_Archaea.fasta
grep -c CCTGGG.AGTACG..CGC RRNA_Bact_Archaea.fasta
grep -c NAATTGACGGGG..C.GC RRNA_Bact_Archaea.fasta
grep -c TTGACGGGG..C.GCACA RRNA_Bact_Archaea.fasta
grep -c TGACGGGG..C.GCACAA RRNA_Bact_Archaea.fasta
grep -c ATTGACGGGG..C.GCAC RRNA_Bact_Archaea.fasta
grep -c AATTGACGGGG..C.GCA RRNA_Bact_Archaea.fasta
grep -c G.CCN.ACTCCT.CGGGA RRNA_Bact_Archaea.fasta
grep -c AAA.NAAT.GACGGGG.C RRNA_Bact_Archaea.fasta
grep -c CGG.CCN.AC.CCTACGG RRNA_Bact_Archaea.fasta
grep -c GG.CCN.AC.CCTACGGG RRNA_Bact_Archaea.fasta
grep -c G.ACTGAGA.ACGG.CCN RRNA_Bact_Archaea.fasta
grep -c GGAGGCAGCAGT..GN.A RRNA_Bact_Archaea.fasta
grep -c ACGG.CCN.ACTCCT.CG RRNA_Bact_Archaea.fasta
grep -c GG.ACTGAGA.ACGG.CC RRNA_Bact_Archaea.fasta
grep -c GAGGCAGCAGT..GN.AT RRNA_Bact_Archaea.fasta
grep -c ACGGGAGGC.GCAGT..G RRNA_Bact_Archaea.fasta
grep -c CGCAAG..T.AAACTCAA RRNA_Bact_Archaea.fasta
grep -c GCAAG..T.AAACTCAAA RRNA_Bact_Archaea.fasta
grep -c ACGGGG..C.GCACAAGC RRNA_Bact_Archaea.fasta
grep -c ACTGAGA.ACGG.CCN.A RRNA_Bact_Archaea.fasta
grep -c GGGAGGC.GCAGT..GNA RRNA_Bact_Archaea.fasta
grep -c CTGAGA.ACGG.CCN.AC RRNA_Bact_Archaea.fasta
grep -c CGTGCCAGC..C.GCGGT RRNA_Bact_Archaea.fasta
grep -c TG.GG.TTAATTCGA.GN RRNA_Bact_Archaea.fasta
